# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DB.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(350, 10, 541, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.query_gBox = QtWidgets.QGroupBox(self.frame)
        self.query_gBox.setGeometry(QtCore.QRect(10, 10, 521, 121))
        self.query_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.query_gBox.setObjectName("query_gBox")
        self.widget = QtWidgets.QWidget(self.query_gBox)
        self.widget.setGeometry(QtCore.QRect(10, 40, 501, 71))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 7, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_4, 1, 4, 1, 2)
        self.comboBox_5 = QtWidgets.QComboBox(self.widget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_5, 1, 6, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.widget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_6, 1, 7, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 1, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 2)
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setGeometry(QtCore.QRect(50, 140, 381, 27))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qu_pushButton = QtWidgets.QPushButton(self.widget1)
        self.qu_pushButton.setObjectName("qu_pushButton")
        self.horizontalLayout.addWidget(self.qu_pushButton)
        self.qu_preview_btn = QtWidgets.QPushButton(self.widget1)
        self.qu_preview_btn.setObjectName("qu_preview_btn")
        self.horizontalLayout.addWidget(self.qu_preview_btn)
        self.qu_help_btn = QtWidgets.QPushButton(self.splitter)
        self.qu_help_btn.setObjectName("qu_help_btn")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(350, 210, 541, 191))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.statistic_gBox = QtWidgets.QGroupBox(self.frame_2)
        self.statistic_gBox.setGeometry(QtCore.QRect(10, 10, 521, 131))
        self.statistic_gBox.setAutoFillBackground(False)
        self.statistic_gBox.setStyleSheet("border-color: rgb(239, 41, 41);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.statistic_gBox.setObjectName("statistic_gBox")
        self.layoutWidget = QtWidgets.QWidget(self.statistic_gBox)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 30, 141, 89))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.total_dog_no_lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.total_dog_no_lineEdit_2.setObjectName("total_dog_no_lineEdit_2")
        self.gridLayout_3.addWidget(self.total_dog_no_lineEdit_2, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.total_cat_no_lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.total_cat_no_lineEdit_2.setObjectName("total_cat_no_lineEdit_2")
        self.gridLayout_3.addWidget(self.total_cat_no_lineEdit_2, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.total_price_lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.total_price_lineEdit_2.setObjectName("total_price_lineEdit_2")
        self.gridLayout_3.addWidget(self.total_price_lineEdit_2, 2, 1, 1, 1)
        self.gridLayout_3.setColumnMinimumWidth(0, 5)
        self.gridLayout_3.setColumnMinimumWidth(1, 1)
        self.gridLayout_3.setColumnStretch(0, 5)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.widget2 = QtWidgets.QWidget(self.statistic_gBox)
        self.widget2.setGeometry(QtCore.QRect(12, 32, 171, 89))
        self.widget2.setObjectName("widget2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.widget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.total_dog_no_lineEdit = QtWidgets.QLineEdit(self.widget2)
        self.total_dog_no_lineEdit.setObjectName("total_dog_no_lineEdit")
        self.gridLayout.addWidget(self.total_dog_no_lineEdit, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.total_cat_no_lineEdit = QtWidgets.QLineEdit(self.widget2)
        self.total_cat_no_lineEdit.setObjectName("total_cat_no_lineEdit")
        self.gridLayout.addWidget(self.total_cat_no_lineEdit, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.total_price_lineEdit = QtWidgets.QLineEdit(self.widget2)
        self.total_price_lineEdit.setObjectName("total_price_lineEdit")
        self.gridLayout.addWidget(self.total_price_lineEdit, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(320, 160, 91, 17))
        self.label_19.setObjectName("label_19")
        self.total_price_label = QtWidgets.QLabel(self.frame_2)
        self.total_price_label.setGeometry(QtCore.QRect(410, 160, 67, 17))
        self.total_price_label.setStyleSheet("color: rgb(239, 41, 41);\n"
"font: 75 15pt \"Ubuntu Condensed\";")
        self.total_price_label.setObjectName("total_price_label")
        self.widget3 = QtWidgets.QWidget(self.frame_2)
        self.widget3.setGeometry(QtCore.QRect(20, 150, 271, 27))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sta_help_btn = QtWidgets.QPushButton(self.widget3)
        self.sta_help_btn.setObjectName("sta_help_btn")
        self.horizontalLayout_2.addWidget(self.sta_help_btn)
        self.sta_obtain_btn = QtWidgets.QPushButton(self.widget3)
        self.sta_obtain_btn.setObjectName("sta_obtain_btn")
        self.horizontalLayout_2.addWidget(self.sta_obtain_btn)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 4)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 321, 391))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pet_img_gBox = QtWidgets.QGroupBox(self.frame_3)
        self.pet_img_gBox.setGeometry(QtCore.QRect(20, 10, 281, 331))
        self.pet_img_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.pet_img_gBox.setObjectName("pet_img_gBox")
        self.pet_img_label = QtWidgets.QLabel(self.pet_img_gBox)
        self.pet_img_label.setGeometry(QtCore.QRect(20, 40, 251, 271))
        self.pet_img_label.setObjectName("pet_img_label")
        self.widget4 = QtWidgets.QWidget(self.frame_3)
        self.widget4.setGeometry(QtCore.QRect(20, 350, 281, 27))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.img_help_btn = QtWidgets.QPushButton(self.widget4)
        self.img_help_btn.setObjectName("img_help_btn")
        self.horizontalLayout_3.addWidget(self.img_help_btn)
        self.img_upload_btn = QtWidgets.QPushButton(self.widget4)
        self.img_upload_btn.setObjectName("img_upload_btn")
        self.horizontalLayout_3.addWidget(self.img_upload_btn)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 4)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 410, 321, 231))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.intro_gBox = QtWidgets.QGroupBox(self.frame_4)
        self.intro_gBox.setGeometry(QtCore.QRect(10, 20, 301, 201))
        self.intro_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.intro_gBox.setObjectName("intro_gBox")
        self.intro_plainTextEdit = QtWidgets.QPlainTextEdit(self.intro_gBox)
        self.intro_plainTextEdit.setGeometry(QtCore.QRect(10, 30, 281, 161))
        self.intro_plainTextEdit.setObjectName("intro_plainTextEdit")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(350, 410, 541, 231))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.ops_gBox = QtWidgets.QGroupBox(self.frame_5)
        self.ops_gBox.setGeometry(QtCore.QRect(10, 20, 521, 201))
        self.ops_gBox.setObjectName("ops_gBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.ops_gBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 501, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 7, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_7, 1, 0, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_8, 1, 4, 1, 2)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_9, 1, 6, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_10, 1, 7, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_11, 1, 3, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_12, 1, 1, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 4, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 1, 1, 2)
        self.ops_sell_btn = QtWidgets.QPushButton(self.ops_gBox)
        self.ops_sell_btn.setGeometry(QtCore.QRect(310, 160, 89, 25))
        self.ops_sell_btn.setObjectName("ops_sell_btn")
        self.trans_help_btn = QtWidgets.QPushButton(self.ops_gBox)
        self.trans_help_btn.setGeometry(QtCore.QRect(50, 160, 88, 25))
        self.trans_help_btn.setObjectName("trans_help_btn")
        self.ops_add_btn = QtWidgets.QPushButton(self.ops_gBox)
        self.ops_add_btn.setGeometry(QtCore.QRect(170, 160, 89, 25))
        self.ops_add_btn.setObjectName("ops_add_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.query_gBox.setToolTip(_translate("MainWindow", "pet attributes"))
        self.query_gBox.setTitle(_translate("MainWindow", "Query"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Gender"))
        self.label_9.setText(_translate("MainWindow", "Price"))
        self.comboBox.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "dog"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.label_5.setText(_translate("MainWindow", "Color"))
        self.label_2.setText(_translate("MainWindow", "Class"))
        self.qu_pushButton.setText(_translate("MainWindow", "Load"))
        self.qu_preview_btn.setText(_translate("MainWindow", "Preview"))
        self.qu_help_btn.setText(_translate("MainWindow", "help"))
        self.statistic_gBox.setTitle(_translate("MainWindow", "Pets Statistic"))
        self.label_10.setText(_translate("MainWindow", "Eldest Pet"))
        self.label_11.setText(_translate("MainWindow", "Eldest Age"))
        self.label_12.setText(_translate("MainWindow", " Price"))
        self.label_6.setText(_translate("MainWindow", "Number of Dog"))
        self.label_7.setText(_translate("MainWindow", "Number of Cat"))
        self.label_8.setText(_translate("MainWindow", "Total Price"))
        self.label_19.setText(_translate("MainWindow", "Total Price:"))
        self.total_price_label.setText(_translate("MainWindow", "100"))
        self.sta_help_btn.setText(_translate("MainWindow", "help"))
        self.sta_obtain_btn.setText(_translate("MainWindow", "Obtain"))
        self.pet_img_gBox.setTitle(_translate("MainWindow", "Pet Image:"))
        self.pet_img_label.setText(_translate("MainWindow", "pet"))
        self.img_help_btn.setText(_translate("MainWindow", "help"))
        self.img_upload_btn.setText(_translate("MainWindow", "upload"))
        self.intro_gBox.setTitle(_translate("MainWindow", "Introduction"))
        self.intro_plainTextEdit.setPlainText(_translate("MainWindow", "Pet Management System helps pet store holders to manage information of all dogs and cats in the store.\n"
""))
        self.ops_gBox.setTitle(_translate("MainWindow", "Transaction"))
        self.label_13.setText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "Gender"))
        self.label_15.setText(_translate("MainWindow", "Price"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "dog"))
        self.label_16.setText(_translate("MainWindow", "Age"))
        self.label_17.setText(_translate("MainWindow", "Color"))
        self.label_18.setText(_translate("MainWindow", "Class"))
        self.ops_sell_btn.setText(_translate("MainWindow", "sell"))
        self.trans_help_btn.setText(_translate("MainWindow", "help"))
        self.ops_add_btn.setText(_translate("MainWindow", "Add"))


