# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DB.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pet_img_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.pet_img_gBox.setGeometry(QtCore.QRect(20, 20, 321, 351))
        self.pet_img_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.pet_img_gBox.setObjectName("pet_img_gBox")
        self.pet_img_label = QtWidgets.QLabel(self.pet_img_gBox)
        self.pet_img_label.setGeometry(QtCore.QRect(20, 40, 251, 251))
        self.pet_img_label.setObjectName("pet_img_label")
        self.img_help_btn = QtWidgets.QPushButton(self.pet_img_gBox)
        self.img_help_btn.setGeometry(QtCore.QRect(40, 320, 80, 25))
        self.img_help_btn.setObjectName("img_help_btn")
        self.img_upload_btn = QtWidgets.QPushButton(self.pet_img_gBox)
        self.img_upload_btn.setGeometry(QtCore.QRect(160, 320, 80, 25))
        self.img_upload_btn.setObjectName("img_upload_btn")
        self.query_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.query_gBox.setGeometry(QtCore.QRect(370, 20, 451, 171))
        self.query_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.query_gBox.setObjectName("query_gBox")
        self.label = QtWidgets.QLabel(self.query_gBox)
        self.label.setGeometry(QtCore.QRect(30, 50, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.query_gBox)
        self.label_2.setGeometry(QtCore.QRect(90, 50, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.query_gBox)
        self.label_3.setGeometry(QtCore.QRect(150, 50, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.query_gBox)
        self.label_4.setGeometry(QtCore.QRect(300, 50, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.query_gBox)
        self.label_5.setGeometry(QtCore.QRect(220, 50, 67, 17))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.query_gBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 80, 51, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.query_gBox)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 80, 51, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.query_gBox)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 80, 51, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.query_gBox)
        self.comboBox_4.setGeometry(QtCore.QRect(210, 80, 51, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.query_gBox)
        self.comboBox_5.setGeometry(QtCore.QRect(300, 80, 51, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.qu_pushButton = QtWidgets.QPushButton(self.query_gBox)
        self.qu_pushButton.setGeometry(QtCore.QRect(90, 130, 89, 25))
        self.qu_pushButton.setObjectName("qu_pushButton")
        self.qu_preview_btn = QtWidgets.QPushButton(self.query_gBox)
        self.qu_preview_btn.setGeometry(QtCore.QRect(210, 130, 89, 25))
        self.qu_preview_btn.setObjectName("qu_preview_btn")
        self.label_9 = QtWidgets.QLabel(self.query_gBox)
        self.label_9.setGeometry(QtCore.QRect(370, 50, 67, 17))
        self.label_9.setObjectName("label_9")
        self.comboBox_6 = QtWidgets.QComboBox(self.query_gBox)
        self.comboBox_6.setGeometry(QtCore.QRect(370, 80, 51, 25))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.qu_help_btn = QtWidgets.QPushButton(self.query_gBox)
        self.qu_help_btn.setGeometry(QtCore.QRect(350, 130, 89, 25))
        self.qu_help_btn.setObjectName("qu_help_btn")
        self.statistic_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.statistic_gBox.setGeometry(QtCore.QRect(370, 200, 278, 162))
        self.statistic_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.statistic_gBox.setObjectName("statistic_gBox")
        self.gridLayout = QtWidgets.QGridLayout(self.statistic_gBox)
        self.gridLayout.setObjectName("gridLayout")
        self.total_cat_no_lineEdit = QtWidgets.QLineEdit(self.statistic_gBox)
        self.total_cat_no_lineEdit.setObjectName("total_cat_no_lineEdit")
        self.gridLayout.addWidget(self.total_cat_no_lineEdit, 1, 2, 1, 1)
        self.total_price_lineEdit = QtWidgets.QLineEdit(self.statistic_gBox)
        self.total_price_lineEdit.setObjectName("total_price_lineEdit")
        self.gridLayout.addWidget(self.total_price_lineEdit, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.statistic_gBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.statistic_gBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 2)
        self.total_dog_no_lineEdit = QtWidgets.QLineEdit(self.statistic_gBox)
        self.total_dog_no_lineEdit.setObjectName("total_dog_no_lineEdit")
        self.gridLayout.addWidget(self.total_dog_no_lineEdit, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.statistic_gBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.sta_obtain_btn = QtWidgets.QPushButton(self.statistic_gBox)
        self.sta_obtain_btn.setObjectName("sta_obtain_btn")
        self.gridLayout.addWidget(self.sta_obtain_btn, 3, 1, 1, 2)
        self.sta_help_btn = QtWidgets.QPushButton(self.statistic_gBox)
        self.sta_help_btn.setObjectName("sta_help_btn")
        self.gridLayout.addWidget(self.sta_help_btn, 3, 0, 1, 1)
        self.ops_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ops_gBox.setGeometry(QtCore.QRect(70, 390, 421, 80))
        self.ops_gBox.setObjectName("ops_gBox")
        self.ops_sell_btn = QtWidgets.QPushButton(self.ops_gBox)
        self.ops_sell_btn.setGeometry(QtCore.QRect(30, 40, 89, 25))
        self.ops_sell_btn.setObjectName("ops_sell_btn")
        self.ops_add_btn = QtWidgets.QPushButton(self.ops_gBox)
        self.ops_add_btn.setGeometry(QtCore.QRect(190, 40, 89, 25))
        self.ops_add_btn.setObjectName("ops_add_btn")
        self.intro_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.intro_gBox.setGeometry(QtCore.QRect(510, 380, 321, 221))
        self.intro_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.intro_gBox.setObjectName("intro_gBox")
        self.intro_plainTextEdit = QtWidgets.QPlainTextEdit(self.intro_gBox)
        self.intro_plainTextEdit.setGeometry(QtCore.QRect(10, 30, 281, 181))
        self.intro_plainTextEdit.setObjectName("intro_plainTextEdit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(100, 520, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pet_img_gBox.setTitle(_translate("MainWindow", "Pet Image:"))
        self.pet_img_label.setText(_translate("MainWindow", "pet"))
        self.img_help_btn.setText(_translate("MainWindow", "help"))
        self.img_upload_btn.setText(_translate("MainWindow", "upload"))
        self.query_gBox.setTitle(_translate("MainWindow", "Query"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Class"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.label_4.setText(_translate("MainWindow", "Gender"))
        self.label_5.setText(_translate("MainWindow", "Color"))
        self.comboBox.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "dog"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "dog"))
        self.qu_pushButton.setText(_translate("MainWindow", "Load"))
        self.qu_preview_btn.setText(_translate("MainWindow", "Preview"))
        self.label_9.setText(_translate("MainWindow", "Price"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "dog"))
        self.qu_help_btn.setText(_translate("MainWindow", "help"))
        self.statistic_gBox.setTitle(_translate("MainWindow", "Statistic"))
        self.label_6.setText(_translate("MainWindow", "Number of Dog"))
        self.label_7.setText(_translate("MainWindow", "Number of Cat"))
        self.label_8.setText(_translate("MainWindow", "Total Price"))
        self.sta_obtain_btn.setText(_translate("MainWindow", "Obtain"))
        self.sta_help_btn.setText(_translate("MainWindow", "help"))
        self.ops_gBox.setTitle(_translate("MainWindow", "Operations"))
        self.ops_sell_btn.setText(_translate("MainWindow", "sell"))
        self.ops_add_btn.setText(_translate("MainWindow", "Add"))
        self.intro_gBox.setTitle(_translate("MainWindow", "Introduction"))
        self.intro_plainTextEdit.setPlainText(_translate("MainWindow", "Pet Management System helps pet store holders to manage information of all pets in the store.\n"
"\n"
"1. In Query frame, through \"load\", you can load all pets attributes to the combobox; after the chosen of every attribute in the combobox, press \"Preview\", the pet image can be seen in the Pet Image frame."))


